spring.datasource.url=jdbc:postgresql://${DB_HOST_HOMOLOG:localhost}:${DB_PORT_HOMOLOG:5432}/${DB_NAME_HOMOLOG:americobarber_homolog}
spring.datasource.username=${DB_USER_HOMOLOG:postgres}
spring.datasource.password=${DB_PASSWORD_HOMOLOG:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET_HOMOLOG:Am3r1c0B4rb3rS3cr3tK3yF0rH0m0l0g4t10n}
logging.level.com.americobarber=INFO

app.cors.allowed-origins=https://americobarber-hml.zynexium.com
