spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:americobarber_prod}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET_PROD:S0m3V3ryStr0ngS3cr3tKeyF0rPr0ducti0n}
logging.level.com.americobarber=WARN
logging.level.org.springframework.web=ERROR

app.cors.allowed-origins=https://americobarber.zynexium.com
