spring.datasource.url=jdbc:postgresql://localhost:5432/americobarber
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

jwt.secret=Am3r1c0B4rb3rS3cr3tK3yF0rD3v3l0pm3nt
logging.level.com.americobarber=DEBUG

# ====== MAIL CONFIGURATION (GMAIL) ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# COLOQUE SEU EMAIL DO GMAIL AQUI:
spring.mail.username=joaopcs360@gmail.com
# COLOQUE A SENHA DE APP DE 16 DIGITOS AQUI:
spring.mail.password=fkpinezaoawganwu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# ========================================

app.frontend.url=http://localhost:5173
